// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGWtOfYAw0ZcX4YPzZZG3bNdtaI-b3jmw',
    appId: '1:610905609500:web:4f354964470db4f22416d9',
    messagingSenderId: '610905609500',
    projectId: 'habit-tracker-9b819',
    authDomain: 'habit-tracker-9b819.firebaseapp.com',
    storageBucket: 'habit-tracker-9b819.firebasestorage.app',
    measurementId: 'G-0857PQ39TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHsCAhe4L0cSWqkaBfy3hGcziZZTT-oy4',
    appId: '1:610905609500:android:fcac0b913ea046712416d9',
    messagingSenderId: '610905609500',
    projectId: 'habit-tracker-9b819',
    storageBucket: 'habit-tracker-9b819.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAd_6kCepv1E_Ha7QURe4Fze0zCcQmm-U',
    appId: '1:610905609500:ios:db098e60bfe52ee52416d9',
    messagingSenderId: '610905609500',
    projectId: 'habit-tracker-9b819',
    storageBucket: 'habit-tracker-9b819.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAd_6kCepv1E_Ha7QURe4Fze0zCcQmm-U',
    appId: '1:610905609500:ios:db098e60bfe52ee52416d9',
    messagingSenderId: '610905609500',
    projectId: 'habit-tracker-9b819',
    storageBucket: 'habit-tracker-9b819.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGWtOfYAw0ZcX4YPzZZG3bNdtaI-b3jmw',
    appId: '1:610905609500:web:df72e2fd4c04c6d82416d9',
    messagingSenderId: '610905609500',
    projectId: 'habit-tracker-9b819',
    authDomain: 'habit-tracker-9b819.firebaseapp.com',
    storageBucket: 'habit-tracker-9b819.firebasestorage.app',
    measurementId: 'G-JZ807VLTKY',
  );
}
